server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy opzionale se vuoi evitare problemi di CORS in produzione
    # location /api {
    #     proxy_pass https://backend:8443;
    # }
}